// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.startupExperimentPrefs.network.http.http3.retry_different_ip_family", false);
user_pref("app.normandy.user_id", "d4d4f8f6-d154-4d74-8090-52a93b7da93b");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1698010645);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1698010645);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1698010645);
user_pref("app.update.lastUpdateTime.region-update-timer", 1698010645);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1698011184);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1698010645);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1698011242);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1698010645);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{e071a72f-4758-4e34-95fe-e4621d70a8f1}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1698010614);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 137);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f0b0d699-bdda-4fee-891b-64091e91e13e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1698010646);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1698010637569");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1698032237569");
user_pref("browser.search.region", "RU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230807140633");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1698011183");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20230807140633");
user_pref("browser.startup.homepage_override.mstone", "116.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1698011183);
user_pref("browser.topsites.contile.lastFetch", 1698011186);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1698010627189");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "116.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "RU");
user_pref("dom.push.userAgentID", "c02410ff22a542f0b0fdaa7bdf4d10dd");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1698010646);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230807140633");
user_pref("extensions.lastAppVersion", "116.0.2");
user_pref("extensions.lastPlatformVersion", "116.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.quarantinedDomains.list", "autoatendimento.bb.com.br,ibpf.sicredi.com.br,ibpj.sicredi.com.br,internetbanking.caixa.gov.br,www.ib12.bradesco.com.br,www2.bancobrasil.com.br");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"181053f9-8736-4f31-b95a-978d76cce906\",\"pictureinpicture@mozilla.org\":\"1c9f7a27-59d7-4957-8cf7-f22ccf42875e\",\"screenshots@mozilla.org\":\"a90f4c2a-6b49-4748-a0b8-f515461ce98c\",\"webcompat-reporter@mozilla.org\":\"7898b385-c61e-4cad-b2a7-e143ed936aeb\",\"webcompat@mozilla.org\":\"7d57a311-ec82-464a-b97e-d220d879f4ea\",\"default-theme@mozilla.org\":\"ffdc74e5-5c4e-40d3-abe7-6354a477f19e\",\"addons-search-detection@mozilla.com\":\"ad8b80fb-c1a3-4812-88c6-211f08d0ed23\",\"google@search.mozilla.org\":\"f8ad924e-21ad-482f-86d6-1696d08611be\",\"amazondotcom@search.mozilla.org\":\"c39a6617-85fe-4307-b79c-a8d03fbc3f8d\",\"wikipedia@search.mozilla.org\":\"6778e05e-1fbb-48b3-9048-67c29d084eee\",\"bing@search.mozilla.org\":\"a20a46ff-41d2-483a-bdfd-4adc8975ca06\",\"ddg@search.mozilla.org\":\"ef7f8791-174c-4094-84df-ae6b00b65d70\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.hashValue", "94531e267314de661b2205c606283fb066d781e5c11027578f2a3c3aa353437c2289544074a28101b6b6f0179f0fe6bd890a0ae2bb6e1cf9053650472576366c");
user_pref("media.gmp-gmpopenh264.lastDownload", 1698011297);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: null, errorCode: 5, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1698010648);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1698011230);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1698011297);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20230807140633");
user_pref("media.gmp-manager.lastCheck", 1698011230);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"enrollmentId\":\"933122ef-64c8-45d7-a35a-5a345525158e\",\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2023-10-22T21:37:10.662Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "0875dfb9-f596-4111-ac4e-cc0fc62ece59");
user_pref("services.settings.blocklists.addons-bloomfilters.last_check", 1698011215);
user_pref("services.settings.blocklists.gfx.last_check", 1698011215);
user_pref("services.settings.clock_skew_seconds", 17);
user_pref("services.settings.last_update_seconds", 1698011215);
user_pref("services.settings.main.addons-manager-settings.last_check", 1698011215);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1698011215);
user_pref("services.settings.main.hijack-blocklists.last_check", 1698011215);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1698011215);
user_pref("services.settings.main.public-suffix-list.last_check", 1698011215);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1698011215);
user_pref("services.settings.main.search-telemetry-v2.last_check", 1698011215);
user_pref("services.settings.main.sites-classification.last_check", 1698011215);
user_pref("services.settings.main.whats-new-panel.last_check", 1698011215);
user_pref("toolkit.startup.last_success", 1698011181);
user_pref("toolkit.telemetry.cachedClientID", "00d23c5f-95af-4101-bade-876406ce2bf2");
user_pref("toolkit.telemetry.previousBuildID", "20230807140633");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
